### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by XmGao** [XmGao/hexo-baidu-url-push#3]
ReferenceError: path is not defined
    at Hexo.<anonymous> (F:\hexoBlog\node_modules\hexo-baidu-url-push\index.js:3:40)
    at Hexo.tryCatcher (F:\hexoBlog\node_modules\bluebird\js\release\util.js:16:23)
    at Hexo.<anonymous> (F:\hexoBlog\node_modules\bluebird\js\release\method.js:15:34) # #

**Comment by GuoZhijie** [comment]
it didn't fixed？
